**step-1**

**create a DataFrame**

  - We will create a DataFrame using list

  - we will create a DataFrame using dictionary


In [4]:
import pandas as pd


In [5]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [6]:
type(d1)

pandas.core.frame.DataFrame

**step-2**

**provide the Data**

In [7]:
names=['harsha','vardhan','dhoni']
pd.DataFrame(names)

0
0   harsha
1  vardhan
2    dhoni

In [8]:
names=['harsha','vardhan']
age=[20,25]
data=zip(names,age)
pd.DataFrame(data)


0   1
0   harsha  20
1  vardhan  25

In [9]:
names=['vardhan','harsha','dhoni']
age=[20,25030]
city=['HYD','VIJ','BLR']
pd.DataFrame(zip(names,age,city))

0      1    2
0  vardhan     20  HYD
1   harsha  25030  VIJ

In [6]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

**step-5**

**Add a new column on existing data frame**

In [11]:
#create a dataframe
#Name
# age 
# city
import pandas as pd
names=['harsha','surnder','raja']
age=[20,35,25]
city=['HYD','VIJ','BLR']
data = zip(names, age, city)
column=['Names', 'Age','City']
df=pd.DataFrame(data, index=city, columns=column)
df

Names  Age City
HYD   harsha   20  HYD
VIJ  surnder   35  VIJ
BLR     raja   25  BLR

- If you want to add a new column

- First check how many rows are there

- For example in above dataframe we have 3 rows

- your new column also should have 3 rows

- suppose I want to create a new column:**salary**

- make a list with 3 values

- salary=[10000,20000,30000]

- **synatx**: dataframe[column]=list of values

-  salary=[10000,20000,30000]

-  df[salary]='salary'

In [19]:
salary=[10000,20000,30000]
df['Salary']=salary

**use case-1**

- Create empty data frame first

- Create 3 list using list comprehesion

- list1= a values from 1 to 10

- list2=square of 1 to 10

- list3= cube of 1 to 10

- Finally make a dataframe

  

In [14]:
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [15]:
l1=[ i for i in range(1,10)]
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
l1=[ i for i in range(1,10)]
l2=[ i**2 for i in range(1,10)]
l3=[ i**3 for i in range(1,10)]

df1['x']=l1
df1['Y']=l2
df1['Z']=l3
df1

x   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**step-6**

**update the  already exist column**


- create a new column

 - Creating a new column the name is our choice

- update existing column are same way only

 - Here also we need a make a list of values = number of rows

 - While updating the existing column

 - we need to provide already existed column name only

 - df['z'] = list of values

In [20]:
#dataframe name: df1
# list of values variable name:z
# which column we want to update : 'z'


z=[i**4 for i in range(1,10)]
df1['Z']=z
df1

x   Y     Z
0  1   1     1
1  2   4    16
2  3   9    81
3  4  16   256
4  5  25   625
5  6  36  1296
6  7  49  2401
7  8  64  4096
8  9  81  6561

In [21]:
df2=pd.DataFrame()
l1=[ i for i in range(1,10)]
l2=[ i**2 for i in range(1,10)]
l3=[ i**3 for i in range(1,10)]

df2['x']=l1
df2['Y']=l2
df2['Z']=l3
df2

x   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**step-7**

**Drop the Column**

In [23]:
df1.columns # how to check the columns

Index(['x', 'Y', 'Z'], dtype='object')

- If you want to drop a specific column

- we will use drop method

- we already know about difference between keywords and methods

- keywords will use directly

- methods will sue with corresponding dataframe

- **method name:drop**


df1.drop()

- column : which column you want to drop

- axis : Represents the specified value is a row or column

  - axis = 0 means rows

  - axis =1 means column

  - by default axis = 0

- inplace : will provide overwrite the dataframe or not

  - inplace=True, this indicates overwrite the dataframe
 
  - inplace=False, this indicates the modified datafrane will be use when you provide n
     new variable for the operation


In [4]:
df2.drop('Y',axis=1)

NameError: name 'df2' is not defined

**Step-8**

**drop the row**

- drop the column and drop the rows both are similar only

- the only difference is axis

  - axis = 0 represnts tows
 
  - by default axis = 0 available
 
  - which means if we provide any value, it will represent rows only
 
  

In [2]:
# dataframe name:df1

import pandas as pd
df2=pd.DataFrame()
l1=[ i for i in range(1,10)]
l2=[ i**2 for i in range(1,10)]
l3=[ i**3 for i in range(1,10)]

df2['x']=l1
df2['Y']=l2
df2['Z']=l3
df2

x   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

In [4]:
df2.drop(4)
# If we run this we will ge error
# by default axis=0 which represent about rows 
# BUt 'X' is a column
# if you want to row, then provide the Row Index

x   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

In [5]:
# multiple rows
#multiple columns keep always in list
df2.drop([4,6])



x   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
5  6  36  216
7  8  64  512
8  9  81  729

In [10]:
df2

x   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

In [28]:
df2([['x']])

TypeError: 'DataFrame' object is not callable

In [11]:
df2.drop([0,1],axis=1)
#[0,1] rows index
# axis =1 columns
#error 

KeyError: '[0, 1] not found in axis'

**step-9**

**How to select the column**

In [21]:
df2['x']
type(df2['x'])

# series type
# NO column name display
# whenever you see this type,always we called series type


pandas.core.series.Series

In [22]:
df2[['x']]

# Data frame type

type(df2[['x']])

pandas.core.frame.DataFrame

In [27]:
df2.x

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: x, dtype: int64

- df2['x']: series type

- df2[['x']] : Dataframe type

- df2.x : Series type

In [29]:
cols=['x','Y','Z']
df2[cols]

x   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

In [31]:
import pandas as pd 
df2['x'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

- All values comes in an array

- Array means it is a list of elements only reprents using numpy package

- Generally elements present in 4 Ways

   - List : Basic representation
 
   - NUmpy array: Array with Numpy Package
 
   - Tensors : Tensor flow package
 
   - Torch : pytorch package 

In [32]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [33]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [34]:
tensor([1,2,3,4])

NameError: name 'tensor' is not defined

In [36]:


list1=[1,2,3,4]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [37]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [38]:
df2['x'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [41]:
 df2['X']=df2['x'].values
df2

x   Y    Z  X
0  1   1    1  1
1  2   4    8  2
2  3   9   27  3
3  4  16   64  4
4  5  25  125  5
5  6  36  216  6
6  7  49  343  7
7  8  64  512  8
8  9  81  729  9

**step-10**

**How to save the Dataframe**

- Dataframes we can save in two framats

   - csv : comma seperated value
 
   - xlsx : excel format
 
- in order to save any data

    - where you want to save : directory name
 
    - What is the name of the file for sorting
 
    - What is the extension
 
  - we already seen same in file handling session

In [ ]:
#case-1 : Saving file at same location

# NO need to provide directory path
# directly give only name of the file
# and extension


In [44]:
#Dataframe name : df2
df2.to_csv('Data1.csv')
df2.to_excel('Data1.xlsx')

**step-11**

**How to read a Dataframe**

In [45]:
import pandas as pd
pd.read_csv('Data1.csv')

Unnamed: 0  x   Y    Z  X
0           0  1   1    1  1
1           1  2   4    8  2
2           2  3   9   27  3
3           3  4  16   64  4
4           4  5  25  125  5
5           5  6  36  216  6
6           6  7  49  343  7
7           7  8  64  512  8
8           8  9  81  729  9

In [46]:
pd.read_excel('Data1.xlsx')

Unnamed: 0  x   Y    Z  X
0           0  1   1    1  1
1           1  2   4    8  2
2           2  3   9   27  3
3           3  4  16   64  4
4           4  5  25  125  5
5           5  6  36  216  6
6           6  7  49  343  7
7           7  8  64  512  8
8           8  9  81  729  9

**Step-12**

** How to avoid index column**

- while we save the dataframe
- 
- auotamatically a  new column  will create

- that we need to avoid

- permission denied means close the data file from laptop

In [47]:
#save the data with out index column
df2.to_csv('Data1.csv',index=False)
df2.to_excel('Data1.xlsx',index=False)

In [51]:
# read the data
import pandas as pd
pd.read_csv('Data1.csv')

x   Y    Z  X
0  1   1    1  1
1  2   4    8  2
2  3   9   27  3
3  4  16   64  4
4  5  25  125  5
5  6  36  216  6
6  7  49  343  7
7  8  64  512  8
8  9  81  729  9